export const accordians = [
  {
    id: 'overview',
    label: 'Overview',
    fieldType: 'string',
    initialState: true,
    showColumns: true,
    fields: [
      'id',
      'joiningDate',
      'manager',
      'location',
      'workMode',
      'yearsOfExperience',
    ],
  },
  {
    id: 'project',
    label: 'Assigned Projects',
    fieldType: 'array-objects',
    initialState: false,
    fields: ['projects$projectName'],
  },
  {
    id: 'skills',
    label: 'Current skills',
    fieldType: 'array',
    initialState: false,
    fields: ['skills'],
  },
  {
    id: 'performance',
    label: 'Performance',
    showColumns: true,
    initialState: false,
    fieldType: 'string',
    fields: ['rating', 'attendancePercentage', 'employeeSatisfaction'],
  },
  {
    id: 'personalInfo',
    label: 'Personal Information',
    showColumns: true,
    initialState: false,
    fieldType: 'string',
    fields: ['email', 'phone'],
  },
  {
    id: 'salary',
    label: 'Salary',
    fieldType: 'string',
    initialState: false,
    fields: ['salary'],
  },
];
